---
resources:
- bases/telemetry.kyma-project.io_logpipelines.yaml
- bases/telemetry.kyma-project.io_logparsers.yaml
- bases/telemetry.kyma-project.io_tracepipelines.yaml
- bases/operator.kyma-project.io_telemetries.yaml
- bases/telemetry.kyma-project.io_metricpipelines.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
