apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-priority-class-high
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: telemetry
    kyma-project.io/module: telemetry
  {{- include "telemetry-manager.labels" . | nindent 4 }}
description: Global scheduling priority of Telemetry DaemonSet components. Must not
  be blocked by unschedulable non-daemonset workloads.
globalDefault: false
value: 2100000
