apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-module
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: telemetry
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    kyma-project.io/module: telemetry
  {{- include "telemetry-manager.labels" . | nindent 4 }}
data: {{ .Files.Get "files/telemetries-busola-config.yaml" | nindent 2 }}
