name: kyma-project.io/module/telemetry
channel: fast
version: 1.6.0
manifest: telemetry-manager.yaml
security: sec-scanners-config.yaml
defaultCR: ./samples/operator_v1beta1_telemetry.yaml
annotations:
  operator.kyma-project.io/doc-url: https://kyma-project.io/#/telemetry-manager/user/README
