apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "telemetry-manager.fullname" . }}-mutating-webhook.kyma-project.io
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "telemetry-manager.fullname" . }}-
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: telemetry
    kyma-project.io/module: telemetry
  {{- include "telemetry-manager.labels" . | indent 4 }}
webhooks:
- name: mutating-metricpipelines-v1beta1.kyma-project.io
  clientConfig:
    service:
      name: telemetry-manager-webhook
      namespace: kyma-system
      path: /mutate-telemetry-kyma-project-io-v1beta1-metricpipeline
      port: 443
  admissionReviewVersions:
    - v1beta1
    - v1
  sideEffects: None
  failurePolicy: Fail
  matchPolicy: Exact
  timeoutSeconds: 15
  namespaceSelector: {}
  objectSelector: {}
  rules:
    - apiGroups:
        - telemetry.kyma-project.io
      apiVersions:
        - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - metricpipelines
      scope: '*'
- name: mutating-tracepipelines-v1beta1.kyma-project.io
  clientConfig:
    service:
      name: telemetry-manager-webhook
      namespace: kyma-system
      path: /mutate-telemetry-kyma-project-io-v1beta1-tracepipeline
      port: 443
  admissionReviewVersions:
    - v1beta1
    - v1
  sideEffects: None
  failurePolicy: Fail
  matchPolicy: Exact
  timeoutSeconds: 15
  namespaceSelector: {}
  objectSelector: {}
  rules:
    - apiGroups:
        - telemetry.kyma-project.io
      apiVersions:
        - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - tracepipelines
      scope: '*'
- name: mutating-logpipelines-v1beta1.kyma-project.io
  clientConfig:
    service:
      name: telemetry-manager-webhook
      namespace: kyma-system
      path: /mutate-telemetry-kyma-project-io-v1beta1-logpipeline
      port: 443
  admissionReviewVersions:
    - v1beta1
    - v1
  sideEffects: None
  failurePolicy: Fail
  matchPolicy: Exact
  timeoutSeconds: 15
  namespaceSelector: {}
  objectSelector: {}
  rules:
    - apiGroups:
        - telemetry.kyma-project.io
      apiVersions:
        - v1beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - logpipelines
      scope: '*'

- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: '{{ include "telemetry-manager.fullname" . }}-manager-webhook'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-telemetry-kyma-project-io-v1alpha1-metricpipeline
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mutating-metricpipelines-v1alpha1.kyma-project.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - telemetry.kyma-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricpipelines
    scope: '*'
  sideEffects: None
  timeoutSeconds: 15
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: '{{ include "telemetry-manager.fullname" . }}-manager-webhook'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-telemetry-kyma-project-io-v1alpha1-tracepipeline
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mutating-tracepipelines-v1alpha1.kyma-project.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - telemetry.kyma-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tracepipelines
    scope: '*'
  sideEffects: None
  timeoutSeconds: 15
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: '{{ include "telemetry-manager.fullname" . }}-manager-webhook'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-telemetry-kyma-project-io-v1alpha1-logpipeline
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: mutating-logpipelines-v1alpha1.kyma-project.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - telemetry.kyma-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - logpipelines
    scope: '*'
  sideEffects: None
  timeoutSeconds: 15
