apiVersion: operator.kyma-project.io/v1alpha1
kind: Telemetry
metadata:
  labels:
    app.kubernetes.io/name: telemetry
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: telemetry-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-operator
  name: default
spec:
  metric:
    gateway:
      scaling:
        type: Static
        static:
          replicas: 4

