apiVersion: v2
name: telemetry-manager
description: Kyma Telemetry Manager Helm Chart
version: 1.57.1
type: application
appVersion: "1.57.1"
keywords:
  - kyma
  - telemetry
  - observability
  - monitoring
  - logging
  - tracing
  - opentelemetry
maintainers:
  - name: kyma-project.io
    url: https://kyma-project.io
dependencies:
  - name: experimental
    version: 1.57.1
    condition: experimental.enabled
  - name: default
    version: 1.57.1
    condition: default.enabled
