global:
  caBundle:
    enabled: false
    name: "custom-ca-certificates"
  imagePullSecret:
    enabled: false
    name: "oci-registry-pullsecret"
experimental:
  enabled: true
default:
  enabled: false
manager:
  container:
    args:
      cert-dir: "/tmp"
      high-priority-class-name: "telemetry-priority-class-high"
      normal-priority-class-name: "telemetry-priority-class"
    env:
      alpineImage: europe-docker.pkg.dev/kyma-project/prod/external/library/alpine:3.23.2
      appLogLevel: info
      fluentBitExporterImage: europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20260116-88440ede
      fluentBitImage: europe-docker.pkg.dev/kyma-project/prod/external/fluent/fluent-bit:4.2.2
      gomemlimit: 300MiB
      otelCollectorImage: europe-docker.pkg.dev/kyma-project/prod/kyma-otel-collector:0.143.0-main
      selfMonitorImage: europe-docker.pkg.dev/kyma-project/prod/tpi/telemetry-self-monitor:3.9.1-0877cc3
      operateInFipsMode: false
    image:
      repository: europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:main
      pullPolicy: "IfNotPresent"
    resources:
      limits:
        memory: 384Mi
      requests:
        cpu: 5m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
managerMetrics:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
managerWebhook:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
additionalMetadata:
  labels:
  # custom-label: my-value
  annotations:
# custom-resource-annotation: my-value
