name: Check Release Branch

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "release-*"
jobs:
  validate-envs:
    name: Validate .env file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Verify .env file has no main branch references
        run: |
          if grep -q "main" .env; then
            echo "The .env file contains references to the main branch"
            exit 1
          fi
