name: Check Release Branch

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "release-*"
jobs:
  validate-envs:
    name: Validate .env file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Verify .env file has no main branch references
        run: |
          if grep -q "main" .env; then
            echo "The .env file contains references to the main branch"
            exit 1
          fi
