name: PR Integration

env:
  IMG: europe-docker.pkg.dev/kyma-project/dev/telemetry-manager:PR-${{ github.event.number }}

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  e2e-metrics:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: cluster info
      shell: bash
      run: |
        kubectl cluster-info
        kubectl -n kyma-system get po

    - name: run tests
      run: make run-e2e-test-metrics

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-traces-release:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        release: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: run tests
      run: make run-e2e-test-tracing

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-traces:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: run tests
      run: make run-e2e-test-tracing

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-logs-release:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        release: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: run tests
      run: make run-e2e-test-logging

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()
    - name: Send slack message on failure
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  e2e-logs:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: run tests
      run: make run-e2e-test-logging

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()
    - name: Send slack message on failure
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  e2e-integration-istio:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: run tests
      run: make run-integration-test-istio

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()
