name: PR Integration

env:
  IMG: europe-docker.pkg.dev/kyma-project/dev/telemetry-manager:PR-${{ github.event.number }}

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  e2e-metrics-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare test
        uses: "./.github/template/prepare-test"
        with:
          release: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: make run-e2e-test-metrics

      - name: Finalize test
        uses: "./.github/template/finalize-test"
        if: success() || failure()
        with:
          failure: failure()

  e2e-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Prepare test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: make run-e2e-test-metrics

    - name: Finalize test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-traces-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        release: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: make run-e2e-test-tracing

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-traces:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: make run-e2e-test-tracing

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-logs-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        release: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: make run-e2e-test-logging

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: make run-e2e-test-logging

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()

  e2e-telemetry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare Test
        uses: "./.github/template/prepare-test"
        with:
          release: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: make run-e2e-test-telemetry

      - name: Finalize Test
        uses: "./.github/template/finalize-test"
        if: success() || failure()
        with:
          failure: failure()

  e2e-telemetry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare Test
        uses: "./.github/template/prepare-test"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: make run-e2e-test-telemetry

      - name: Finalize Test
        uses: "./.github/template/finalize-test"
        if: success() || failure()
        with:
          failure: failure()

  e2e-integration-istio:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Prepare Test
      uses: "./.github/template/prepare-test"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: make run-integration-test-istio

    - name: Finalize Test
      uses: "./.github/template/finalize-test"
      if: success() || failure()
      with:
        failure: failure()
