name: Sync External Images

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "external-images.yaml"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - "external-images.yaml"

jobs:
  sync-external-images:
    permissions:
      id-token: write # Required for requesting the JWT token
      contents: read
    uses: kyma-project/test-infra/.github/workflows/image-syncer.yml@main
    with:
      debug: true
