name: sync-external-images

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "external-images.yaml"
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    branches:
      - main
    paths:
      - "external-images.yaml"



jobs:
  sync-external-images:
    permissions:
      id-token: write # This is required for requesting the JWT token
    uses: kyma-project/test-infra/.github/workflows/image-syncer.yml@main
    with:
      debug: true
